name: Run pipeline
on:
  push:
    paths-ignore:
    - collection/resource/**
    - collection/log/**
    - index/**
    - var/**
    branches: main
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch: null
env:
  DLB_BOT_EMAIL: ${{ secrets.DLB_BOT_EMAIL }}
  DLB_BOT_TOKEN: ${{ secrets.DLB_BOT_TOKEN }}
  DLB_BOT_USERNAME: ${{ secrets.DLB_BOT_USERNAME }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_S3_SECRET_ACCESS_KEY}}
        aws-region: eu-west-2
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Setup git
      run: 'git config user.email "${DLB_BOT_EMAIL}"

        git config user.name "${DLB_BOT_USERNAME}"

        git remote set-url origin https://${DLB_BOT_USERNAME}:${DLB_BOT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

        git checkout ${GITHUB_REF##*/}

        '
    - name: Update makerules
      run: make makerules
    - name: Commit updated makerules
      run: make commit-makerules
    - name: Install dependencies
      run: make init
    - name: Fetch dataset files from S3
      run: make fetch-s3
    - name: Run the collector
      run: make collect
    - name: Commit collection
      run: make commit-collection
    - name: Update the collection dataset
      run: make collection
    - name: Commit collection
      run: make commit-collection
    - name: push collection files to S3
      run: make push-collection-s3
    - name: Run the pipeline to make the dataset
      run: make dataset
    - name: Push dataset files to S3
      run: make push-dataset-s3
